# Generated by Django 5.2.1 on 2025-05-28 07:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Xona nomi')),
                ('room_type', models.CharField(choices=[('single', 'Yakka xonali'), ('double', 'Ikki xonali'), ('suite', 'Lyuks'), ('family', 'Oilaviy')], max_length=20, verbose_name='Xona turi')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Narxi (kunlik)')),
                ('description', models.TextField(verbose_name='Tavsif')),
                ('image', models.ImageField(upload_to='rooms/', verbose_name='Rasm')),
                ('is_available', models.BooleanField(default=True, verbose_name='Mavjudmi')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Xona',
                'verbose_name_plural': 'Xonalar',
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100, verbose_name="To'liq ismi")),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone', models.CharField(max_length=20, verbose_name='Telefon')),
                ('check_in', models.DateField(verbose_name='Kelish sanasi')),
                ('check_out', models.DateField(verbose_name='Ketish sanasi')),
                ('guests', models.IntegerField(verbose_name='Mehmonlar soni')),
                ('special_requests', models.TextField(blank=True, verbose_name='Maxsus talablar')),
                ('status', models.CharField(choices=[('pending', 'Kutilmoqda'), ('confirmed', 'Tasdiqlangan'), ('cancelled', 'Bekor qilingan')], default='pending', max_length=20, verbose_name='Holati')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Umumiy narx')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.room', verbose_name='Xona')),
            ],
            options={
                'verbose_name': 'Buyurtma',
                'verbose_name_plural': 'Buyurtmalar',
                'ordering': ['-created_at'],
            },
        ),
    ]
